/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-sm': ['2.25rem', { lineHeight: '2.5rem', fontWeight: '600' }],
        'headline-sm': ['1.5rem', { lineHeight: '2rem', fontWeight: '500' }],
        'title-md': ['1.125rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', fontWeight: '700', letterSpacing: '0.05em' }],
      },
      colors: {
        background: '#faf8ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eef0ff',
        'inverse-primary': '#b2c5ff',
        'inverse-surface': '#283044',
        'on-background': '#131b2e',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#c4d2ff',
        'on-primary-fixed': '#001848',
        'on-primary-fixed-variant': '#0040a2',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#57657a',
        'on-secondary-fixed': '#0d1c2e',
        'on-secondary-fixed-variant': '#3a485b',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434654',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffc6b2',
        'on-tertiary-fixed': '#380d00',
        'on-tertiary-fixed-variant': '#812800',
        outline: '#737685',
        'outline-variant': '#c3c6d6',
        primary: '#003d9b',
        'primary-container': '#0052cc',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b2c5ff',
        secondary: '#515f74',
        'secondary-container': '#d5e3fc',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#b9c7df',
        surface: '#faf8ff',
        'surface-bright': '#faf8ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-container-low': '#f2f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d2d9f4',
        'surface-tint': '#0c56d0',
        'surface-variant': '#dae2fd',
        tertiary: '#7b2600',
        'tertiary-container': '#a33500',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59b',
      }
    },
  },
  plugins: [],
}
